FROM openjdk:17-jdk-slim

# Copy AppDynamics agent
COPY docker/appdynamics/appdynamics-agent /appdynamics-agent

# Copy the built JAR file
COPY build/libs/hello-world-app-0.0.1-SNAPSHOT.jar /app.jar

# Expose port
EXPOSE 8080

# Set environment-specific profile
ENV SPRING_PROFILES_ACTIVE=integration
ENV JAVA_OPTS="-javaagent:/appdynamics-agent/javaagent.jar"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app.jar"]